package:
  name: repex
  version: !!str 0.1.X

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - mdtraj
    - openmm
    - openmmtools    
    - pymbar
    - netcdf4
    - mpi4py
  run:
    - python
    - pandas
    - scipy
    - mdtraj
    - openmm
    - openmmtools
    - pymbar
    - netcdf4
    - mpi4py
    - pyzmq 
    - clusterutils

test:
  requires:
    - nose
    - pyzmq    
  imports:
    - repex
  commands:
    - nosetests repex --nocapture --verbosity=2 --with-doctest --logging-level=WARN  -a '!slow'

about:
  home: https://github.com/choderalab/repex
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

